include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unused_element: ignore
    unnecessary_null_comparison: ignore
    constant_identifier_names: ignore
    unnecessary_string_interpolations: ignore
    prefer_const_constructors: ignore
    non_constant_identifier_names: ignore
    use_build_context_synchronously: ignore
    type_literal_in_constant_pattern: ignore
    unused_local_variable: ignore
    avoid_unnecessary_containers: ignore
    no_leading_underscores_for_local_identifiers: ignore
    library_prefixes: ignore
