name: versa_app_tutorial_cleanarch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  auto_route: ^7.4.0
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1    
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  json_annotation: ^4.9.0
  font_awesome_flutter: ^10.8.0
  tab_indicator_styler: ^2.0.0
  intl: ^0.20.1
  socket_io_client: ^3.0.2
  shimmer: ^3.0.0
  flutter_local_notifications: ^18.0.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  gradient_borders: ^1.0.1
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0    
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  freezed: ^2.5.7

  

flutter:
  uses-material-design: true
  fonts:
    - family: DBHeaven
      fonts:
        - asset: assets/fonts/DBHeaven_Normal.ttf
        - asset: assets/fonts/DBHeavent_Bold.ttf
          weight: 700
        - asset: assets/fonts/DBHeavent_Italic.ttf
          style: italic
        - asset: assets/fonts/DBHeavent_Bold_Italic.ttf
          weight: 700
          style: italic
  assets:
    - assets/images/
    - assets/svg/transfer/
    - assets/svg/buy/
    - assets/svg/coin/  
    - assets/svg/home/
